document.addEventListener('DOMContentLoaded', () => {
    // DOM Elements
    const body = document.documentElement; // using root for rem adjustments if needed or just body
    const contentBody = document.getElementById('content-body');
    const header = document.querySelector('.navbar');
    const btnMinus = document.getElementById('fontSizeMinus');
    const btnPlus = document.getElementById('fontSizePlus');
    const scrollTopBtn = document.getElementById('scrollTopBtn');
    
    // Check if elements exist
    if (!contentBody || !header || !btnMinus || !btnPlus || !scrollTopBtn) {
        console.error('Core elements not found in the DOM.');
        return;
    }
    
    // Configurations
    let lastScrollY = window.scrollY;
    let currentFontSize = 18; // base size matches CSS
    const MIN_FONT_SIZE = 14;
    const MAX_FONT_SIZE = 32;
    const FONT_STEP = 2;
    
    // Initial content sanitization (remove empty paragraphs often generated by word docs)
    const emptyParagraphs = contentBody.querySelectorAll('p:empty');
    emptyParagraphs.forEach(p => p.remove());

    /**
     * Font Size Controls
     */
    const updateFontSize = (newSize) => {
        if (newSize >= MIN_FONT_SIZE && newSize <= MAX_FONT_SIZE) {
            currentFontSize = newSize;
            // Apply only to the readable text content
            contentBody.style.fontSize = `${currentFontSize}px`;
            
            // Provide subtle visual feedback that the state changed
            localStorage.setItem('readerFontSize', currentFontSize);
        }
    };

    // Load saved preference
    const savedSize = localStorage.getItem('readerFontSize');
    if (savedSize) {
        updateFontSize(parseInt(savedSize, 10));
    }

    btnMinus.addEventListener('click', () => {
        updateFontSize(currentFontSize - FONT_STEP);
    });

    btnPlus.addEventListener('click', () => {
        updateFontSize(currentFontSize + FONT_STEP);
    });

    /**
     * Scroll Interactions (Header Hide/Show & Scroll to Top)
     */
    window.addEventListener('scroll', () => {
        const currentScrollY = window.scrollY;
        
        // 1. Navbar auto-hide logic
        // Only hide if we've scrolled down a bit to prevent jitter at the very top
        if (currentScrollY > 60) {
            if (currentScrollY > lastScrollY) {
                // Scrolling down
                header.classList.add('hidden');
            } else {
                // Scrolling up
                header.classList.remove('hidden');
            }
        } else {
            // Always show at the top
            header.classList.remove('hidden');
        }
        
        // 2. Scroll to top button visibility
        if (currentScrollY > 300) {
            scrollTopBtn.classList.add('visible');
        } else {
            scrollTopBtn.classList.remove('visible');
        }
        
        lastScrollY = currentScrollY;
    }, { passive: true });

    // Scroll to top action
    scrollTopBtn.addEventListener('click', () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });
    
    // Process image wrappers to fix overflow generated from word documents
    const docImages = contentBody.querySelectorAll('img');
    docImages.forEach(img => {
        // Ensure parent paragraphs of images don't constrain them weirdly
        if(img.parentElement && img.parentElement.tagName.toLowerCase() === 'p') {
            img.parentElement.style.textAlign = 'center';
            img.parentElement.style.textIndent = '0';
        }
    });
});
